sudo: false

jdk: oraclejdk8
node_js: node

git:
  depth: 2

cache:
  directories:
   - $HOME/.m2
   - $HOME/.npm
   - ./front-end/node_modules
   - ./node_modules

 
jobs:
  include:
   ###### TEST ANGULAR ######
   - stage: Test
     language: node_js
     if: type IN (pull_request)
     script:
      - npm install
      - ng test
      
   ###### TEST MYSQL ######
   - stage: Test
     if: type IN (pull_request)
     env:
      - AUTO=create-drop
      - DATABASE=jdbc:mysql://127.0.0.1:3306/test_db?user=root
      - DATABASE_USER=root
      - DATABASE_PASS=
      - DIALECT=org.hibernate.dialect.MySQL5Dialect
     services:
      - mysql
     before_script:
      - mysql -e 'CREATE DATABASE IF NOT EXISTS test_db;'
     script:
      - cd back-end
      - mvn test -B
      
   ###### TEST POSTGRESQL ######
   - stage: Test
     if: type IN (pull_request)
     env:
      - AUTO=create-drop
      - DATABASE=jdbc:postgresql://127.0.0.1:5432/test_db
      - DATABASE_USER=postgres
      - DATABASE_PASS=
      - DIALECT=org.hibernate.dialect.PostgreSQLDialect
     services:
      - postgresql
     before_script:
      - psql -c 'create database test_db;' -U postgres
     script:
      - cd back-end
      - mvn test -B
      
   ###### DEPLOY ######
   - stage: Package and Deploy
     if: branch = master AND type IN (push)
     before_script:
      - npm install -g @angular/cli
     script:
      - cd front-end
      - npm install
      #- npm run build
      - cd ../back-end
      - rm src/main/resources/.gitignore
      - git add .
      - git commit -m "Package"
      - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B
     after_script:
      - shopt -s extglob
      - rm -rf !(target)
      - cd target
      - rm -rf !($JAR_NAME)
      - cd ..
      - git add .
      - git commit -m "Clear"
     deploy:
       provider: heroku
       api-key: 
         secure: $HEROKU_API_KEY
       app: $HEROKU_APP_NAME
   