sudo: false

jdk: oraclejdk8
node_js: node

git:
  depth: 3

services:
  - mysql
  - postgresql

cache:
  directories:
   - $HOME/.m2
   - $HOME/.npm
   - ./front-end/node_modules
   
branches:
  only:
   - master

 
jobs:
  include:
   - stage: Package and Deploy
     before_script:
      - npm install -g @angular/cli
     script:
      - cd front-end
      - npm install
      - npm run build
      - cd ..
      - cd back-end
      - cd src/main/resources/static
      - ls -a
      - cd ../../../..
      - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B
     deploy:
       provider: heroku
       api-key: 
         secure: $HEROKU_API_KEY
       app: prueba-ci-69
   