sudo: false

services:
  - mysql
  - postgresql

cache:
  directories:
   - $HOME/.m2

  
matrix:
  include:
   - language: java
     jdk: oraclejdk8
     env:
      - AUTO=update
      - DATABASE=jdbc:postgresql://127.0.0.1:5432/db_example
      - DATABASE_PASS=1234
      - DATABASE_USER=tester
      - DIALECT=org.hibernate.dialect.PostgreSQLDialect
     
     before_script:
      - psql -c 'create database db_example;' -U postgres
      - psql -c "CREATE USER tester WITH PASSWORD '1234';" -U postgres
     
     script:
      - cd back-end
      - mvn package -DskipTests=false -Dmaven.javadoc.skip=true -B
 
     deploy:
       provider: heroku
       api-key: 
         secure: $HEROKU_API_KEY
       app: prueba-ci-69
