sudo: false

services:
  - mysql
  - postgresql

cache:
  directories:
   - $HOME/.m2

  
matrix:
  include:
   - language: java
     jdk: oraclejdk8
     
     script:
      - cd back-end
      - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B
 
     deploy:
       provider: heroku
       api-key: 
         secure: $HEROKU_API_KEY
       app: prueba-ci-69
